[project]
name = "zadan"
version = "0.1.0"
description = "mizanan ?"
authors = [
    {name = "serpico"}
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    'requests'
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
